import { admitScreen } from './admit.mjs';
import { AindfError, sha256 } from './util.mjs';
export const GENERATED_MARK = '// @generated by aindf-kit';
/** Deterministic Next.js App Router page for an admitted screen. Props are emitted as JSON data only. */
export function generateNextPage(bundle, screen, { screenPath, screenBytes }) {
  const admitted = admitScreen(bundle, screen);
  if (!admitted.ok) throw new AindfError('SCREEN_REJECTED', admitted.errors.map(e => `${e.code} ${e.path}`).join('; '));
  const contracts = new Map(bundle.sources.components.components.map(c => [c.name, c]));
  const used = new Set();
  const jsx = (n, indent, extraChildren = []) => {
    const c = contracts.get(n.component); used.add(c.export);
    const pad = ' '.repeat(indent);
    const props = { ...(n.props ?? {}) };
    const slotAttrs = [];
    let children = [...extraChildren];
    for (const [slot, nodes] of Object.entries(n.slots ?? {})) {
      const prop = c.slotProps?.[slot] ?? slot;
      if (prop === 'children') children = [...children, ...nodes];
      else slotAttrs.push(`${prop}={<>\n${nodes.map(x => jsx(x, indent + 2)).join('\n')}\n${pad}</>}`);
    }
    const attrs = [...Object.entries(props).map(([k, v]) => `${k}={${JSON.stringify(v)}}`), c.routeParams ? 'routeParams={routeParams}' : '', ...slotAttrs].filter(Boolean).join(' ');
    const open = `${pad}<${c.export}${attrs ? ' ' + attrs : ''}`;
    return children.length ? `${open}>\n${children.map(x => jsx(x, indent + 2)).join('\n')}\n${pad}</${c.export}>` : `${open}/>`;
  };
  // The template renders the sections as its children; its own declared slots go to their slot props (0d3e7edd review).
  const body = jsx({ ...screen.template, slots: { ...(screen.template.slots ?? {}) } }, 4, screen.sections);
  const needsParams = [...screen.sections].some(function walk(n) { return contracts.get(n.component).routeParams || Object.values(n.slots ?? {}).flat().some(walk); });
  const imports = new Set(used);
  const exportsCode = [];
  const metaEntries = Object.entries(screen.meta ?? {});
  if (metaEntries.length) {
    for (const [, v] of metaEntries) if (typeof v === 'object') imports.add(v.binding);
    exportsCode.push(`export const metadata = { ${metaEntries.map(([k, v]) => `${k}: ${typeof v === 'object' ? v.binding : JSON.stringify(v)}`).join(', ')} };`);
  }
  if (screen.params) {
    imports.add(screen.params.binding);
    if (screen.params.dynamicParams !== undefined) exportsCode.push(`export const dynamicParams = ${screen.params.dynamicParams};`);
    exportsCode.push(`export function generateStaticParams() { return ${screen.params.binding}(); }`);
  }
  const header = `${GENERATED_MARK} from ${screenPath} (sha256 ${sha256(screenBytes)}) against DS ${bundle.ds.id}@${bundle.ds.version} (bundle ${bundle.bundleSha256}). Do not edit: the build regenerates and compares this file.`;
  const signature = needsParams ? `export default async function AindfScreen({ params }: { params: Promise<Record<string, string>> }) {\n  const routeParams = await params;\n` : 'export default function AindfScreen() {\n';
  return `${header}\nimport { ${[...imports].sort().join(', ')} } from ${JSON.stringify(bundle.implementation.module)};\n${exportsCode.length ? '\n' + exportsCode.join('\n') + '\n' : ''}\n${signature}  return (\n${body}\n  );\n}\n`;
}
/** Maps a screen route to its App Router page file. */
export const pageFileForRoute = route => `${route === '/' ? '' : route.slice(1) + '/'}page.tsx`;
