import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, readdirSync, writeFileSync, cpSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadDs, checkDs, createBundle, verifyBundle, admitScreen, generateNextPage, buildScreens, createDsMcp, bundlePin } from '../src/index.mjs';
const fixture = fileURLToPath(new URL('./fixtures/tiny-ds/', import.meta.url));
const load = () => loadDs(join(fixture, 'aindf.config.json'));
const bundle = createBundle(load());
const screen = (over = {}) => ({ kind: 'aindf.screen', aindfVersion: '0.2', ds: bundlePin(bundle), route: '/start', template: { component: 'Page', props: { title: 'Start' } },
  sections: [{ component: 'Hero', props: { tone: 'bold' }, slots: { title: [{ component: 'Heading', props: { text: 'Hello' } }], actions: [{ component: 'Cta', props: { label: 'Join', action: 'signup' } }] } }], ...over });
const codes = s => admitScreen(bundle, s).errors.map(e => e.code);
const mutate = f => { const s = structuredClone(screen()); f(s); return s; };

test('a second, unrelated design system conforms and bundles: the kit carries no DS of its own', () => {
  assert.deepEqual(checkDs(load()), []);
  assert.equal(verifyBundle(bundle).ds.id, 'tiny');
  for (const file of readdirSync(new URL('../src/', import.meta.url))) assert.doesNotMatch(readFileSync(new URL(`../src/${file}`, import.meta.url), 'utf8'), /qfactory|qf-|@\/components/i, file);
});

test('conformance rejects forbidden props, layer rule, dangling edges and upward tokens', () => {
  const ds = load();
  ds.sources.components.components[3].props.className = { type: 'text' };
  ds.sources.slots.slotsets[0].slots[1].accepts.layers.push('sections');
  ds.sources.presets.presets[0].builtOn = 'Ghost';
  ds.sources.tokens.tokens[0] = { name: 'blue-500', tier: 'foundations', alias: 'color-accent' };
  ds.sources.components.components[3].props.action.bindings = ['launchMissiles'];
  const found = new Set(checkDs(ds).map(e => e.code));
  for (const code of ['FORBIDDEN_PROP', 'LAYER_RULE', 'DANGLING_PRESET', 'TOKEN_TIER', 'TOKEN_DIRECTION', 'UNKNOWN_BINDING']) assert.ok(found.has(code), code);
  assert.throws(() => createBundle(ds), /DS_NOT_CONFORMANT/);
});

test('an allowed screen passes admission', () => assert.deepEqual(admitScreen(bundle, screen()), { ok: true, errors: [] }));

test('hostile screens fail with stable codes', () => {
  const cases = [
    ['UNKNOWN_PROP', s => { s.sections[0].props.className = 'x'; }],
    ['UNKNOWN_PROP', s => { s.sections[0].slots.title[0].props.style = { color: 'red' }; }],
    ['UNKNOWN_PROP', s => { s.sections[0].slots.actions[0].props.onClick = 'alert(1)'; }],
    ['UNKNOWN_FIELD', s => { s.sections[0].html = '<script>alert(1)</script>'; }],
    ['UNKNOWN_FIELD', s => { s.css = 'body{display:none}'; }],
    ['UNKNOWN_COMPONENT', s => { s.sections.push({ component: 'Carousel' }); }],
    ['DS_PIN_MISMATCH', s => { s.ds.bundleSha256 = 'a'.repeat(64); }],
    ['SLOT_REJECTS', s => { s.sections[0].slots.title = [{ component: 'Cta', props: { label: 'x', action: 'signup' } }]; }],
    ['SLOT_CARDINALITY', s => { s.sections[0].slots.title = []; }],
    ['UNKNOWN_SLOT', s => { s.sections[0].slots.footer = []; }],
    ['INVALID_ENUM', s => { s.sections[0].props.tone = 'neon'; }],
    ['UNKNOWN_BINDING', s => { s.sections[0].slots.actions[0].props.action = 'fetch("https://evil")'; }],
    ['MISSING_PROP', s => { delete s.template.props.title; }],
    ['INVALID_TEXT', s => { s.sections[0].slots.title[0].props.text = 'x'.repeat(41); }],
    ['NOT_A_TEMPLATE', s => { s.template = { component: 'Hero' }; }],
    ['LAYER_MISMATCH', s => { s.sections.push({ component: 'Heading', props: { text: 'loose' } }); }],
    ['SCREEN_SHAPE', s => { s.route = '/../../etc'; }],
  ];
  for (const [code, f] of cases) assert.ok(codes(mutate(f)).includes(code), `${code}: ${codes(mutate(f))}`);
});

test('codegen is deterministic, emits props as JSON data only and imports only the DS module', () => {
  const bytes = Buffer.from(JSON.stringify(screen()));
  const a = generateNextPage(bundle, screen(), { screenPath: 's.json', screenBytes: bytes });
  assert.equal(a, generateNextPage(bundle, screen(), { screenPath: 's.json', screenBytes: bytes }));
  assert.match(a, /^\/\/ @generated by aindf-kit/);
  assert.deepEqual([...a.matchAll(/^import .* from (.+);$/gm)].map(m => m[1]), ['"@tiny/ds"']);
  const tricky = mutate(s => { s.sections[0].slots.title[0].props.text = '"}}/><script>x'; });
  assert.throws(() => generateNextPage(bundle, mutate(s => { s.sections[0].props.className = 'x'; }), { screenPath: 's', screenBytes: bytes }), /SCREEN_REJECTED/);
  const code = generateNextPage(bundle, { ...tricky, sections: [{ ...tricky.sections[0], slots: { ...tricky.sections[0].slots, title: [{ component: 'Heading', props: { text: '"}}/><script>' } }] } }] }, { screenPath: 's', screenBytes: bytes });
  assert.match(code, /text=\{"\\"}}\/><script>"\}/);
});

test('build --check fails on a hand-edited, missing, stale or orphan generated page', () => {
  const dir = mkdtempSync(join(tmpdir(), 'aindf-build-'));
  cpSync(fixture, join(dir, 'ds'), { recursive: true });
  mkdirSync(join(dir, 'screens')); mkdirSync(join(dir, 'app'));
  writeFileSync(join(dir, 'screens/start.screen.json'), JSON.stringify(screen(), null, 2));
  const opts = { configPath: join(dir, 'ds/aindf.config.json'), screensDir: join(dir, 'screens'), appDir: join(dir, 'app'), root: dir };
  assert.throws(() => buildScreens({ ...opts, check: true }), /GENERATED_MISSING/);
  const { receipts } = buildScreens(opts);
  assert.equal(receipts[0].state, 'built');
  buildScreens({ ...opts, check: true });
  writeFileSync(join(dir, 'app/start/page.tsx'), readFileSync(join(dir, 'app/start/page.tsx'), 'utf8').replace('Hello', 'Hacked'));
  assert.throws(() => buildScreens({ ...opts, check: true }), /GENERATED_DRIFT/);
  buildScreens(opts);
  const tokens = JSON.parse(readFileSync(join(dir, 'ds/tokens.json'))); tokens.tokens[0].value = '#ff0000';
  writeFileSync(join(dir, 'ds/tokens.json'), JSON.stringify(tokens));
  assert.throws(() => buildScreens({ ...opts, check: true }), /SCREEN_REJECTED.*DS_PIN_MISMATCH/);
});

test('MCP serves the AINDF query surface, validates, and stages only with an author token', async () => {
  const stored = new Map();
  const staging = { authorize: token => token === 'author-1' ? 'author-1' : null, put: async (key, bytes) => { const created = !stored.has(key); if (created) stored.set(key, bytes); return { created }; } };
  const handle = createDsMcp(bundle, { staging });
  const call = async (name, args, auth) => (await handle({ jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name, arguments: args } }, { auth })).result;
  assert.equal((await handle({ jsonrpc: '2.0', id: 0, method: 'initialize', params: {} })).result.serverInfo.name, 'aindf-ds-tiny');
  const tools = (await handle({ jsonrpc: '2.0', id: 1, method: 'tools/list' })).result.tools.map(t => t.name);
  for (const t of ['list-by-facet', 'slot-accepts', 'applicable-modifiers', 'get-preset', 'get-ds', 'get-component', 'validate-screen', 'submit-screen', 'request-extension']) assert.ok(tools.includes(t), t);
  assert.deepEqual((await call('get-ds')).structuredContent.pin, bundlePin(bundle));
  assert.equal((await call('slot-accepts', { component: 'Hero', slot: 'title' })).structuredContent.cardinality, '1..1');
  assert.equal((await call('applicable-modifiers', { component: 'Cta' })).structuredContent[0].category, 'tone');
  assert.equal((await call('validate-screen', { screen: screen() })).structuredContent.ok, true);
  assert.equal((await call('validate-screen', { screen: mutate(s => { s.sections[0].props.style = 'x'; }) })).structuredContent.ok, false);
  assert.equal((await call('submit-screen', { screen: screen() })).structuredContent.code, 'UNAUTHORIZED');
  assert.equal((await call('submit-screen', { screen: screen() }, 'forged')).structuredContent.code, 'UNAUTHORIZED');
  assert.equal((await call('submit-screen', { screen: mutate(s => { s.sections[0].props.className = 'x'; }) }, 'author-1')).structuredContent.state, 'rejected');
  const ok = (await call('submit-screen', { screen: screen() }, 'author-1')).structuredContent;
  assert.equal(ok.state, 'draft');
  assert.ok([...stored.keys()].some(k => k.endsWith(`${ok.id}.screen.json`)));
  assert.equal((await call('request-extension', { need: 'a carousel' }, 'author-1')).structuredContent.state, 'requested');
  assert.equal((await createDsMcp(bundle)({ jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'submit-screen', arguments: { screen: screen() } } })).result.structuredContent.code, 'READ_ONLY');
  assert.throws(() => createDsMcp({ ...bundle, ds: { ...bundle.ds, version: '9.9.9' } }), /BUNDLE_INTEGRITY/);
});

test('review 0d3e7edd: prototype keys cannot pass as declared props or fields', () => {
  for (const key of ['constructor', 'toString', 'hasOwnProperty', '__proto__', 'valueOf']) {
    const s = JSON.parse(JSON.stringify(screen()).replace('"tone":"bold"', `"tone":"bold","${key}":"x"`));
    assert.ok(codes(s).includes('UNKNOWN_PROP'), `prop ${key}: ${codes(s)}`);
    const top = JSON.parse(JSON.stringify(screen()).replace('"kind":', `"${key}":"x","kind":`));
    assert.ok(codes(top).includes('UNKNOWN_FIELD'), `screen field ${key}: ${codes(top)}`);
    const node = JSON.parse(JSON.stringify(screen()).replace('"component":"Hero"', `"component":"Hero","${key}":{}`));
    assert.ok(codes(node).includes('UNKNOWN_FIELD'), `node field ${key}: ${codes(node)}`);
  }
});

test('review 0d3e7edd: template slots are rendered, not dropped', () => {
  const s = mutate(x => { x.template.slots = { banner: [{ component: 'Heading', props: { text: 'Banner' } }] }; });
  assert.equal(admitScreen(bundle, s).ok, true);
  const code = generateNextPage(bundle, s, { screenPath: 's', screenBytes: Buffer.from('x') });
  assert.match(code, /<Page title=\{"Start"\} banner=\{<>\n\s+<Heading text=\{"Banner"\}\/>\n\s+<\/>\}>/);
  assert.match(code, /<Hero /);
  assert.ok(codes(mutate(x => { x.template.slots = { banner: [{ component: 'Cta', props: { label: 'x', action: 'signup' } }] }; })).includes('SLOT_REJECTS'));
  const ds = load(); ds.sources.components.components[0].slotProps = { banner: 'children' };
  assert.ok(checkDs(ds).some(e => e.code === 'TEMPLATE_CHILDREN_SLOT'));
});

// review of #9: a 2000-character cut by UTF-16 units split an emoji, the server built a lone surrogate itself and
// refused its own record; the cut is by code points now, and a client's lone surrogate is a tool error, not a crash
test('MCP request-extension: an emoji at the cut stays whole; a lone surrogate from the client is a tool error and nothing is staged', async () => {
  const puts = [];
  const staging = { authorize: () => 'author-1', put: async (key, bytes) => { puts.push({ key, bytes }); return { created: true }; } };
  const handle = createDsMcp(bundle, { staging });
  const call = async args => (await handle({ jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'request-extension', arguments: args } }, { auth: 't' })).result;
  const ok = await call({ need: 'x'.repeat(1999) + '😀tail' });
  assert.equal(ok.structuredContent.ok, true, JSON.stringify(ok));
  assert.equal(JSON.parse(puts[0].bytes).need, 'x'.repeat(1999) + '😀');
  const bad = await call({ need: 'broken \ud800' });
  assert.equal(bad.isError, true);
  assert.equal(bad.structuredContent.code, 'NOT_I_JSON');
  assert.match(bad.structuredContent.message, /^\$\.need: string has a lone surrogate$/);
  assert.equal(puts.length, 1, 'nothing staged for the refused request');
});

// review of #9 (G11): conformance accepted an object as the default of a number prop
test('[AINDF-DS-32] a prop default must be a value a screen could set; a valid default passes', async () => {
  const { loadDs, checkDs } = await import('../src/index.mjs');
  const fresh = () => loadDs(new URL('./fixtures/tiny-ds/aindf.config.json', import.meta.url).pathname);
  const at = (ds, name, prop) => ds.sources.components.components.find(c => c.name === name).props[prop];
  const ok = fresh(); at(ok, 'Hero', 'tone').default = at(ok, 'Hero', 'tone').values[0];
  ok.sources.components.components.find(c => c.name === 'Hero').props.size = { type: 'number', minimum: 0, maximum: 10, default: 10 };
  assert.deepEqual(checkDs(ok), []);
  for (const [why, mutate, path] of [
    ['object on a number (the G11 case)', ds => { ds.sources.components.components.find(c => c.name === 'Hero').props.size = { type: 'number', minimum: 0, maximum: 10, default: { 10: 1 } }; }, 'components.Hero.props.size.default'],
    ['number outside its range', ds => { ds.sources.components.components.find(c => c.name === 'Hero').props.size = { type: 'number', minimum: 0, maximum: 10, default: 11 }; }, 'components.Hero.props.size.default'],
    ['object on an enum', ds => { at(ds, 'Hero', 'tone').default = { 10: 1 }; }, 'components.Hero.props.tone.default'],
    ['value outside the enum', ds => { at(ds, 'Hero', 'tone').default = 'nope'; }, 'components.Hero.props.tone.default'],
    ['number on a text', ds => { at(ds, 'Heading', 'text').default = 3; }, 'components.Heading.props.text.default'],
    ['binding outside the allowlist', ds => { at(ds, 'Cta', 'action').default = 'other'; }, 'components.Cta.props.action.default'],
  ]) { const ds = fresh(); mutate(ds); assert.deepEqual(checkDs(ds).map(e => `${e.code} ${e.path}`), [`INVALID_DEFAULT ${path}`], why); }
});

// review of #10: examples were not checked — an MCP could show a "good" example that admission refuses
test('[AINDF-DS-33] a good example must admit and a bad one must not; matching examples pass', async () => {
  const { loadDs, checkDs } = await import('../src/index.mjs');
  const fresh = examples => { const ds = loadDs(new URL('./fixtures/tiny-ds/aindf.config.json', import.meta.url).pathname); ds.sources.components.components.find(c => c.name === 'Cta').examples = examples; return ds; };
  assert.deepEqual(checkDs(fresh({ good: [{ label: 'Join', action: 'signup' }], bad: [{ label: 'Go', className: 'x' }, { action: 'signup' }] })), []);
  for (const [why, examples, want] of [
    ['good with an unknown prop', { good: [{ label: 'Join', action: 'signup', className: 'x' }] }, 'INVALID_EXAMPLE components.Cta.examples.good[0].props.className'],
    ['good with an invalid value', { good: [{ label: 'Join', action: 'nope' }] }, 'INVALID_EXAMPLE components.Cta.examples.good[0].props.action'],
    ['good missing a required prop', { good: [{ action: 'signup' }] }, 'INVALID_EXAMPLE components.Cta.examples.good[0].props'],
    ['bad that admits', { bad: [{ label: 'Join', action: 'signup' }] }, 'INVALID_EXAMPLE components.Cta.examples.bad[0]'],
  ]) assert.deepEqual(checkDs(fresh(examples)).map(e => `${e.code} ${e.path}`), [want], why);
});

// review of #11: a bad example can name the refusal it shows ($expect); without it, any refusal counts
test('[AINDF-DS-33] a bad example with $expect must be refused with that code', async () => {
  const { loadDs, checkDs } = await import('../src/index.mjs');
  const fresh = examples => { const ds = loadDs(new URL('./fixtures/tiny-ds/aindf.config.json', import.meta.url).pathname); ds.sources.components.components.find(c => c.name === 'Cta').examples = examples; return ds; };
  assert.deepEqual(checkDs(fresh({ bad: [{ label: 'Go', className: 'x', $expect: 'UNKNOWN_PROP' }, { action: 'signup', $expect: 'MISSING_PROP' }] })), []);
  assert.deepEqual(checkDs(fresh({ bad: [{ label: 'Go', action: 'signup', className: 'x', $expect: 'MISSING_PROP' }] })).map(e => `${e.code} ${e.path}`), ['INVALID_EXAMPLE components.Cta.examples.bad[0].$expect']);
  assert.deepEqual(checkDs(fresh({ bad: [{ label: 'Go', action: 'signup', $expect: 'UNKNOWN_PROP' }] })).map(e => `${e.code} ${e.path}`), ['INVALID_EXAMPLE components.Cta.examples.bad[0]'], 'an admitted bad example still fails first');
  assert.deepEqual(checkDs(fresh({ bad: [{ className: 'x', $expect: 'NOPE' }] })).map(e => e.code), ['SCHEMA'], 'an unknown expected code is a schema error');
});
